# Kitty terminal configuration

include everforest.conf

# Font
font_family             JetBrainsMono Nerd Font
font_size               11

# Appearance
background_opacity      0.92
window_padding_width    8

# Cursor
cursor_shape            beam
cursor_blink_interval   0

# Scrollback
scrollback_lines        10000

# Bell
enable_audio_bell       no

# Window
confirm_os_window_close 0

# Display
linux_display_server    x11
shell /usr/bin/zsh
